[package]
name = "nyx_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnyx={path="./libnyx/libnyx"}
nix = "0.17.0"
